kind: Service
apiVersion: v1
metadata:
  name: csi-minio-controller
  namespace: kube-system
  labels:
    app: "csi-minio"
    role: "controller"
    owner: "ucloud"
spec:
  selector:
    app: "csi-minio"
    role: "controller"
    owner: "ucloud"
  ports:
    - name: dummy
      port: 12345
---
kind: StatefulSet 
apiVersion: apps/v1
metadata:
  name: csi-minio-controller
  namespace: kube-system
spec:
  serviceName: "csi-minio-controller"
  replicas: 1
  selector:
    matchLabels:
      app:  "csi-minio"
      role: "controller"
      owner: "ucloud"
  template:
    metadata:
      labels:
        app:  "csi-minio"
        role: "controller"
        owner: "ucloud"
    spec:
      serviceAccount: csi-minio-controller
      containers:
      - name: csi-provisioner
        image: uhub.service.ucloud.cn/safehouse/csi-provisioner:v1.2.0
        args:
        - "--csi-address=$(ADDRESS)"
        - "--enable-leader-election"
        - "--connection-timeout=30s"
        #- "--extra-create-metadata"
        - "--v=5"
        - "--timeout=600s"
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        imagePullPolicy: "IfNotPresent"
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
      - name: csi-attacher
        image: uhub.service.ucloud.cn/uk8s/csi-attacher:v1.2.1
        args:
        - "--csi-address=$(ADDRESS)"
        - "--leader-election=true"
        - "--leader-election-namespace=kube-system"
        - "--timeout=30s"
        - "--v=5"
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        - name: MY_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        imagePullPolicy: "Always"
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
      - name: cluster-registrar
        image:  uhub.service.ucloud.cn/uk8s/csi-cluster-driver-registrar:v1.0.1
        args:
        - "--csi-address=/csi/csi.sock"
        - "--pod-info-mount-version=v1"
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
      - name: csi-minio
        image: uhub.service.ucloud.cn/safehouse/csi-minio:1.8
        imagePullPolicy: "Always"
        args:
        - "--drivername=minio.csi.ucloud.cn"
        - "--endpoint=$(CSI_ENDPOINT)"
        - "--hostname=$(KUBE_NODE_NAME)"
        - "--maxvolume=100"
        - "--v=5"
        envFrom:
        - configMapRef:
            name: minio-config
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CSI_ENDPOINT
          value: unix://csi/csi.sock
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
      volumes:
      - name: socket-dir
        emptyDir:
