apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: csi-minio
  namespace: kube-system
  labels:
    app: "csi-minio"
    role: "node"
    owner: "ucloud"
spec:
  selector:
    matchLabels:
      app: "csi-minio"
      role: "node"
      owner: "ucloud"
  template:
    metadata:
      labels:
         app: "csi-minio"
         role: "node"
         owner: "ucloud"
    spec:
      serviceAccount: csi-minio-node
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: dedicated
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        key: node.cloudprovider.kubernetes.io/uninitialized
        value: "true"
      hostNetwork: true
      hostPID: true
      containers:
        - name: node-registrar
          image:  uhub.service.ucloud.cn/uk8s/csi-node-driver-registrar:v1.1.0
          imagePullPolicy: "Always"
          args:
            - "--v=5"
            - "--csi-address=/csi/csi.sock"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/minio.csi.ucloud.cn/csi.sock"
          env:
            - name: ADDRESS
              value: unix://csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        - name: csi-minio
          securityContext:
            privileged: true
          # CAP_SYS_ADMIN is required for mount() syscall.
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: uhub.service.ucloud.cn/safehouse/csi-minio:1.17
          args :
            - "--drivername=minio.csi.ucloud.cn"
            - "--hostname=$(KUBE_NODE_NAME)"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--v=7"
            - "--maxvolume=100"
            - "--alsologtostderr=true"
          imagePullPolicy: "Always"
          envFrom:
          - configMapRef:
              name: minio-config
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://var/lib/kubelet/plugins/minio.csi.ucloud.cn/csi.sock
          volumeMounts:
            - name: plugin-dir
              mountPath: /var/lib/kubelet/plugins/minio.csi.ucloud.cn
            - name: user-config
              mountPath: /etc/uk8s/
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet/
              mountPropagation: "Bidirectional"
            - name: host-log
              mountPath: /var/log/ucloud/
            - name: host-dev
              mountPath: /dev
              mountPropagation: "HostToContainer"
      volumes:
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/minio.csi.ucloud.cn/
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet/
            type: Directory
        - name: host-dev
          hostPath:
            path: /dev
        - name: host-log
          hostPath:
            path: /var/log/ucloud/
        - name: user-config
          configMap:
            name: minio-config
